---
title: "qPCR_Conversion"
author: "Jessica Bullington"
date: "4/17/2020"
output: html_document
---

### Set up the markdown file
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import and format the data
```{r comment=NA, message=F, warning=F}
# load the data (note data file must be in this repository)
data <- read.csv("Example_qPCRConversion.csv")
View(data)

# clean up the data file (there is some stuff at the bottom and extra blank rows)
data <- data[-91:-106,] # This removes rows 91-106
View(data)

# assign to the correct data class #warning message about NAs is OK
class(data$Ct.FAM) # check the data class type
data$Ct.FAM <- as.numeric(as.character(data$Ct.FAM)) # change to numeric
data$Amount.FAM..Copies. <- as.numeric(as.character(data$Amount.FAM..Copies.)) # change to numeric
```

### Plot the standard curve
```{r comment=NA, message=F, warning=F, fig.width = 3, fig.height = 3}
# linear regression of standard curve
standards = data[1:24,]
standardCurve <- lm(Ct.FAM ~ log10(Amount.FAM..Copies.), data = standards)
  
standardCurvePlot <- plot(Ct.FAM ~ log10(Amount.FAM..Copies.), data = standards) 
abline(coef(standardCurve)) 
legend("topright", legend=c(paste= "slope", round(standardCurve$coefficients[2], 2), 
                            paste= "intercept", round(standardCurve$coefficients[1], 2), 
                            paste= "R^2", round(summary(standardCurve)$r.squared, 2),
                            paste = "efficiency", round((10^(-1/standardCurve$coefficients[2])-1)*100, 1)))
```

#### Replot the standard curve after removing certain standards
```{r comment=NA, message=F, warning=F, fig.width = 3, fig.height = 3}
# remove standards that sucked and redo analysis NOT NEEDED 21 Jan 2020
#standards <- standards[-1:-3,] # uncomment this line and change which rows to remove
standardCurve <- lm(Ct.FAM ~ log10(Amount.FAM..Copies.), data = standards)

standardCurvePlot <- plot(Ct.FAM ~ log10(Amount.FAM..Copies.), data = standards)
abline(coef(standardCurve))
legend("topright", legend=c(paste= "slope", round(standardCurve$coefficients[2], 2),
                            paste= "intercept", round(standardCurve$coefficients[1], 2),
                            paste= "R^2", round(summary(standardCurve)$r.squared, 2),
                            paste = "efficiency", round((10^(-1/standardCurve$coefficients[2])-1)*100, 1)))
```

### Plot the unknowns on top of the standard curve to ensure interpolating rather than extrapolating
```{r}

```

### Convert cycle threshold to gene copies per mL
```{r comment=NA, message=F, warning=F}
# data set of unknowns including info on standard curve
unknowns = subset(data, Name == "Unknowns")
#unknowns <- unknowns[-1:-3,] # uncomment this line and change which rows to remove if these samples were outside of the standard curve

# add new columns to the data table
unknowns$plate_num = 1 #change to the actual plate number
unknowns$standard_slope = standardCurve$coefficients[2]
unknowns$standard_intercept = standardCurve$coefficients[1]
unknowns$R2 = summary(standardCurve)$r.squared
unknowns$efficiency =  (10^(-1/standardCurve$coefficients[2])-1)*100
  
# add a new column that interpolates copies/well from Ct for the unknowns
unknowns$log.copies.well = ((unknowns$Ct.FAM - standardCurve$coefficients[1])/standardCurve$coefficients[2])
unknowns$copies.well = 10^unknowns$log.copies.well

# copies/ul extract accounting for dilution factor
vol.well = 5 #qPCR template volume in ul
unknowns$vol.well = vol.well
unknowns$copies.ul = ((unknowns$copies.well/vol.well)*unknowns$DilutionFactor)

# copies/extraction
vol.elution = 110 #DNA extraction elution volume in ul
unknowns$vol.elution = vol.elution
unknowns$copies.extraction = (unknowns$copies.ul*vol.elution)

# copies/ml #Volume is volume of sample filtered in mL
unknowns$copies.ml = (unknowns$copies.extraction/unknowns$Volume)


```

### Plot the replicates to check inhibition
```{r}
# make a plot that compares the diluted to undiluted replicates for each sample including dilution factor

```


### Export the data to a csv file
```{r}
# write csv file
write.csv(unknowns, file = "Example_ConvertedData.csv", row.names=FALSE, na="")

# average the replicates (if not strongly inhibited) and make a new file

write.csv(unknowns, file = "Example_ConvertedData_Averaged.csv", row.names=FALSE, na="")
```




