---
title: "Plate3_GenBac_qPCRConversion"
author: "Rayna McClintock"
date: "6/1/2020"
output: html_document
---

### Set up the markdown file
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

### Import and format the data
```{r comment=NA, message=F, warning=F}
# clear workspace
rm(list=ls())

# load the data (note data file must be in this repository)
data <- read.csv("Plate3_GenBac_qPCRConversion.csv")
```

### Plot the standard curve
```{r comment=NA, message=F, warning=F, fig.width = 5, fig.height = 5}
# linear regression of standard curve
standards = subset(data, Name == "STANDARD")
standardCurve <- lm(CT ~ log10(Amount..Copies.), data = standards)

# save the line info
standard_slope = standardCurve$coefficients[2]
standard_intercept = standardCurve$coefficients[1]
R2 = summary(standardCurve)$r.squared
efficiency =  (10^(-1/standardCurve$coefficients[2])-1)*100

# plot standards and best fit line
standardCurvePlot <- plot(CT ~ log10(Amount..Copies.), data = standards, pch=19) 
abline(coef(standardCurve)) 
legend("topright", legend = c(paste= "slope", round(standard_slope, 2), paste= "intercept", round(standard_intercept, 2), paste= "R^2", round(R2, 2), paste = "efficiency", round(efficiency, 1)))
```


### Convert cycle threshold to gene copies per mL using standard curve
```{r comment=NA, message=F, warning=F}
# data set of unknowns including info on standard curve
unknowns = subset(data, Name == "UNKNOWN")

# add new columns to the data table
unknowns$plate_num = 3 # note:change to the actual plate number
unknowns$standard_slope = standard_slope
unknowns$standard_intercept = standard_intercept
unknowns$R2 = R2
unknowns$efficiency = efficiency
  
# add a new column that interpolates copies/well from Ct for the unknowns
unknowns$log.copies.well = (unknowns$CT - standard_intercept)/standard_slope
unknowns$copies.well = 10^unknowns$log.copies.well

# copies/ul extract accounting for dilution factor
vol.well = 3 # note:change to qPCR template volume in ul
unknowns$vol.well = vol.well
unknowns$copies.ul = ((unknowns$copies.well/vol.well)*unknowns$DilutionFactor)

# copies/extraction
vol.elution = 110 #note:change to DNA extraction elution volume in ul
unknowns$vol.elution = vol.elution
unknowns$copies.extraction = (unknowns$copies.ul*vol.elution)

# copies/ml #Volume is volume of sample filtered in mL
unknowns$copies.ml = (unknowns$copies.extraction/unknowns$Volume)
```


### Plot the unknowns on top of the standard curve to ensure interpolating rather than extrapolating
```{r comment=NA, message=F, warning=F, fig.width = 5, fig.height = 5}
# set up the color palette
library(viridis)
unknowns$SampleIDNum = as.factor(as.character(unknowns$SampleIDNum)) # change to factor for colors
Colors = viridis(n=nlevels(unknowns$SampleIDNum)) # set the color levels to call on later

# check the range and adjust the limits in plot
range(unknowns$CT, na.rm=T) # y limits
range(unknowns$log.copies.well, na.rm =T) # x limits

# plot the standard curve again
standardCurvePlot <- plot(CT ~ log10(Amount..Copies.), data = standards,
                          xlim = c(-1,6), ylim = c(22,41),
                          xlab = "Log10(copies/well)",
                          ylab = "CT") 

# add boundaries and standard line
abline(v=log10(10), lty=2)
abline(v=log10(50000), lty=2)
abline(coef(standardCurve)) 

# add the sample data
standardCurvePlot <- points(CT ~ log.copies.well, data = unknowns, pch=19, 
                            col = Colors[unknowns$SampleIDNum])
legend("topright", inset = 0.002, box.lty=0, legend=c(paste= "Slope", round(standardCurve$coefficients[2], 2), 
                                                      paste= "Intercept", round(standardCurve$coefficients[1], 2), 
                                                      paste= "R^2", round(summary(standardCurve)$r.squared, 2),
                                                      paste = "Efficiency", round((10^(-1/standardCurve$coefficients[2])-1)*100, 1)))

```



### Plot the replicates to check inhibition
```{r}
# make a plot that compares the diluted to undiluted replicates for each sample including dilution factor
library("ggplot2")
unknowns$SampleIDNum <- as.numeric(as.character(unknowns$SampleIDNum)) # change to numeric
unknowns$DilutionFactor <- as.factor(as.character(unknowns$DilutionFactor)) # change to factor
qplot(SampleIDNum,log10(copies.ml+1), data=unknowns, col=DilutionFactor)
```


### Export the data to a csv file
```{r}
# write csv file
write.csv(unknowns, file = "Plate3_GenBac_ConvertedData.csv", row.names=FALSE, na="")

# average the replicates (if not strongly inhibited) and make a new file
library(dplyr)
data.average = unknowns %>% group_by(SampleIDNum) %>% summarise(copies.ml = mean(copies.ml, na.rm = T))
write.csv(data.average, file = "Plate3_GenBac_Averaged.csv", row.names=FALSE, na="")
```

